[features]
seeds = false
skip-lint = false
[programs.localnet]
lottery = "HvJymJvJKu1REDZ4Jr6HrzSDNMpTZXsh48PGmjAGa3TS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
